Atcoder site API integration completed.
GDGVIT/code-competition-watcher pull request #16
Opened 2021-01-28 05:42 UTC by abdealijaroli

API integration for Codeforces, CodeChef, and Atcoder websites are completed now. The bot is fully functional for the mentioned sites!

2021-01-28 13:54 UTC, mdhishaamakhtar requested changes

2021-01-28 13:54 UTC, mdhishaamakhtar commented on src/constants.ts
> +  atcoderReply: 'Upcoming contests on Atcoder are - '
use camelCase here too

2021-01-28 13:54 UTC, mdhishaamakhtar commented on src/constants.ts
>    codeChefUrl: 'http://cp-events-api.herokuapp.com/api/v1/codechef',
use camelCase here

2021-01-28 13:55 UTC, mdhishaamakhtar reviewed
Make them camelCase and I'll merge

2021-01-28 14:47 UTC, abdealijaroli commented
Requested changes done

2021-02-01 03:11 UTC, mdhishaamakhtar approved these changes

2021-02-01 03:11 UTC, merged